wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1675811862.711671
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 76
      3:
      - 13
      - 23
      4: 3.9.15
      5: 0.13.9
      8:
      - 5
