name: rdkit2019
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda
##  - tensorflow-gpu
  - ncurses
  - numpy
  - pcre
  - matplotlib
  - pytest
  - pyyaml
  - python
  - rdkit
  - seaborn
#   - tensorboard
  - yaml
  - markdown
#   - scipy
  - pip
##   - scikit-learn
  - pandas
  - keras
  - jsonpickle

