name: Test Pull Request

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}
    - name: install package
      run: pip install -r requirements.txt
    - name: Flake8
      run: flake8
    - name: Black
      uses: psf/black@23.3.0
    - name: Check import order
      uses: isort/isort-action@v1
      with:
        isort-versioin: 5.12.0
        configuration: --check --diff --profile black
    - name: Check typing
      run: mypy dfpl tests
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}
    - name: install pytest
      run: pip install pytest
    - name: install package
      run: pip install -r requirements.txt
    - name: run tests
      run: pytest tests

