name: Test Pull Request

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}
    - name: install package
      run: pip install -r requirements.txt
    - name: Flake8
      run: flake8
    - name: Black
      uses: psf/black@23.3.0
    - name: Check import order
      uses: isort/isort-action@v1
      with:
        isort-version: 5.12.0
        configuration: --check --diff --profile black
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}
    - name: install pytest
      run: pip install pytest
    - name: install package
      run: pip install -r requirements.txt
    - name: run pytests
      run: pytest tests
    - uses: Jimver/cuda-toolkit@v0.2.10
      id: cuda-toolkit
      with:
        cuda: '12.1.0'

    - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

    - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

    - run: nvcc -V

    - name: run test CLI calls for example
      run: |
        set -e
        dfpl train -f example/train.json
        if [ ! -d example/results_train/ ]; then
          echo "training result directory missing" >&2 
          exit 1
        fi
        dfpl predict -f example/predict.json
        if [ ! -d example/results_predict/ ]; then
          echo "predict result directory missing" >&2 
          exit 1
        fi
        dfpl convert -f example/data